let phonedatapage = [
    {
        id: 1,
      text_header1:'iPhone Xs  Max ',
      text_header2:'شاید نسل‌های اخیر آیفون‌ از ایده‌آل جابز فاصله گرفته باشد؛ اما جابز هرگز شانس دیدن بازار این روزهای گوشی‌های هوشمند و تغییر نظرات خود را نداشت. دنیای گوشی‌های هوشمند سکون را بر نمی‌تابد از طرفی مسئولان اپل نیز به خوبی نتایج تلخ شکست بزرگانی چون نوکیا را با چشمان خود نظاره کرده‌اند و دیگر اشتباه پایبندی به اصول در این بازار بی‌رحم را تکرار نخواهند کرد. اپل ساختار طراحی محصولات خود را هر چند سال یکبار بازبینی می‌کند،    آیفون X را باید سرآغاز چهارمین نسل از طراحی‌ محصولات آیفون بدانیم.',
      img_header:"https://cdn01.zoomit.ir/2017/11/fa9b5627-4c4f-4f15-ba97-de60c20b0efb.jpg",
      sliderImg1:'https://cdn.vox-cdn.com/thumbor/QytuXmIKkJXnSXTY-NZ5_rhnczM=/0x0:2040x1360/1200x0/filters:focal(0x0:2040x1360):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/9599227/jbareham_171101_2099_A_0088_02.jpg',
      sliderImg2:'https://cdn.gsm.ir/static/files/image/2017/11/12/iPhone-X-Rview-GSM.ir-024.jpg',
      sliderImg3:'https://cdn.gsm.ir/static/files/image/2017/11/12/iPhone-X-Rview-GSM.ir-016.jpg',
      sliderImg4:'https://cdn.vox-cdn.com/thumbor/0nCfyi6iVtFGRbQJatC1G2cayOE=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/9221083/iphonex_mockup_phonedesigner.jpg',
      sliderImg5:'https://s.yimg.com/uu/api/res/1.2/hAytRMnx4ng6If1P8kIiNg--~B/aD0xMjE3O3c9MjAwMDthcHBpZD15dGFjaHlvbg--/https://o.aolcdn.com/hss/storage/midas/a77372d02698ddbfc44ea16b49bdb0f7/205830010/_MG_4584-2.jpg',
      sliderImg6:'https://cdn.gsm.ir/static/files/image/2017/11/12/iPhone-X-Rview-GSM.ir-033.jpg',
      sliderImg7:'https://cdn.gsm.ir/static/files/image/2017/11/12/iPhone-X-Rview-GSM.ir-027.jpg',
      sliderImg8:'https://cdn.gsm.ir/static/files/image/2017/11/12/iPhone-X-Rview-GSM.ir-022.jpg',
    },

    {
        id: 2,
        text_header1:'iPhone 12 Pro Max A2644',
        text_header2:'طراحی تخت با رنگ‌های جذاب، قدرتمندترین تراشه‌ در دنیای گوشی‌های هوشمند، اتصال 5G، بزرگ‌ترین دوربین تاریخ آیفون با سیستم لرزش‌گیر پیشرفته، نمایشگر ۶٫۷ اینچی، فیلم‌برداری 4K HDR با تمام دوربین‌ها و صدالبته برچسب قیمتی ۱۱۰۰ دلاری؛ آیفون ۱۲ پرو مکس بزرگ‌ترین و البته پیشرفته‌ترین گوشی هوشمند اپل به‌حساب می‌آید و نخستین آیفون پس‌از مدت‌های طولانی است که تغییراتی سخت‌افزاری در ماژول دوربین خود می‌بیند.',
        img_header:"https://cdn01.zoomit.ir/2020/12/apple-iphone-12-pro-max-back-design-from-top.jpg?w=1920",
        sliderImg1:'https://cdn01.zoomit.ir/2020/12/apple-iphone-12-pro-max-blue-stand-on-the-desk-back-design.jpg',
        sliderImg2:'https://cdn01.zoomit.ir/2020/12/apple-iphone-12-pro-max-vs-11-pro-max-back-design-camera-logo.jpg',
        sliderImg3:'https://cdn01.zoomit.ir/2020/12/apple-iphone-12-pro-max-back-logo-and-camera-blue-ocean-color.jpg',
        sliderImg4:'https://www.neuf.tv/wp-content/uploads/2020/11/Apple-iPhone-12-Pro-Max-battery-life-all-good-except-for-this-one-thing.jpg',
        sliderImg5:'https://cdn01.zoomit.ir/2020/12/apple-iphone-12-pro-max-taking-photo-triple-camera.jpg',
        sliderImg6:'https://cdn01.zoomit.ir/2020/12/apple-iphone-12-pro-max-vs-11-pro-max-design-edges.jpg',
        sliderImg7:'https://cdn01.zoomit.ir/2020/12/apple-iphone-12-pro-max-display-ios-14-home-screen.jpg',
        sliderImg8:'https://cdn01.zoomit.ir/2020/12/apple-iphone-12-pro-max-port-lightning-speaker-and-mic-holes.jpg',
    },

    {
        id: 3,
        text_header1:' iPhone 13 Pro Max A2644',
        text_header2:' آیفون ۱۳ پرو با صفحه‌نمایش ۱۲۰ هرتزی و شارژدهی عالی و دوربین کارآمدتر از گذشته، یکی از کامل‌ترین گوشی‌های بازار است. اگر تغییرات ظاهری را کنار بگذاریم، اپل در سال‌های اخیر، بیشتر از هرچیز دیگری، بر بهبود صفحه‌نمایش، تراشه و دوربین آیفون تمرکز داشت. امسال باتری نیز به جمع موارد پراهمیت اضافه شده و نقش دوربین پررنگ‌تر از همیشه است. تفاوت اصلی iPhone 13 با آیفون های سال قبل چیه؟ اگر دنبال جواب این سوال ها هستید حتما تا انتهای این مطلب همراه باشید که به تمام این سوال ها جواب میدیم!',
        img_header:"https://mobonil.com/wp-content/uploads/2021/10/86550242.jpg",
        sliderImg1:'https://www.trustedreviews.com/wp-content/uploads/sites/54/2019/10/iphone11promax-1.jpeg',
        sliderImg2:'https://cloudfront-us-east-1.images.arcpublishing.com/elespectador/GXHMGQ4UAFCA3MUWIIN7NDMCZA.jpg',
        sliderImg3:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvgHSQFfAx84P1EfRNzVGKlLWAgZT3tBfMeA&usqp=CAU',
        sliderImg4:'https://www.apple.com/newsroom/images/product/iphone/lifestyle/Apple_iPhone-11-Pro_Most-Powerful-Advanced_091019_big.jpg.large.jpg',
        sliderImg5:'https://cdn.mos.cms.futurecdn.net/ajR3VMJbmPe9fxThb6CVG4.jpg',
        sliderImg6:'https://bachlongmobile.com/bnews/wp-content/uploads/2021/09/tren-tay-thuc-te-iphone-13-pro-max-819x1024.jpg',
        sliderImg7:'https://www.androidauthority.com/wp-content/uploads/2019/09/iPhone-11-Pro-Max-Rear-in-Hand-e1569854606506.jpg',
        sliderImg8:'https://i.blogs.es/4c5b2b/ipihone-13-pro-00/450_1000.jpeg',
    },
    {
        id: 4,
        text_header1:'Samsung Galaxy S20 Ultra',
        text_header2:'سامسونگ به‌خوبی می‌داند برچسب قیمتی ۱۴۰۰ دلاری و جثه‌ی عظیم گلکسی S20 اولترا، آن را از فهرست خرید بسیاری از علاقه‌مندان سری محبوب Galaxy S خط خواهد زد؛ بنابراین، طبیعی است که به موفقیت دو عضو دیگر خانواده‌ی S20 دل ببندد و بر بازاریابی برای این گوشی‌های هوشمند به‌طورویژه تمرکز کند؛ اما آیا کسانی که به‌دلیل قیمت نجومی یا ابعاد بسیار بزرگ از مدل اولترا گریزان هستند، به خرید گلکسی S20 یا گلکسی S20 پلاس ترغیب خواهند شد؟',
        img_header:"https://fscl01.fonpit.de/userfiles/7687254/image/Samsung_S20_FE_5G/NextPit_Samsung_S20_FE_5G_back.jpg",
        sliderImg1:'https://www.androidheadlines.com/wp-content/uploads/2020/10/Samsung-Galaxy-S20-FE-Review-AM-AH-4.jpg',
        sliderImg2:'https://menworld.pl/wp-content/uploads/2021/04/Samsung-S20-FE-5G_11.jpg',
        sliderImg3:'https://cdn.24net.cz/1/obrazek/ikonka-322360/620w',
        sliderImg4:'https://cdn.mos.cms.futurecdn.net/w73wSycYLravqULw4jMgq5.jpg',
        sliderImg5:'https://cdn01.zoomit.ir/2020/4/ff3fbe9e-577e-4c6a-96ec-48647ceaac97.jpg',
        sliderImg6:'https://obbo.ir/images/Products/20211027163105.jpg',
        sliderImg7:'https://www.digitaltrends.com/wp-content/uploads/2020/03/samsung-galaxy-s20-ultra-ry-12.jpg?fit=720%2C480&p=1',
        sliderImg8:'https://images.samsung.com/is/image/samsung/assets/cl/smartphones/galaxy-s20/images/galaxy-s20_highlight_kv_s.jpg?$ORIGIN_JPG$',
    },
    {
        id: 5,
        text_header1:'Samsung Galaxy S21 Ultra',
        text_header2:'می‌خواهیم به سراغ ساده‌ترین مدل، یعنی گلکسی S21 برویم؛ گوشی پرچم‌داری که کوچک‌ترین، سبک‌ترین و طبیعتا، ارزان‌ترین مدل از این سری به‌حساب می‌آید. به‌نظر می‌رسد این گوشی جایگزینی برای گلکسی S20 FE باشد چراکه از نظر دلاری هم، قیمتی مشابه آن دارد. سال ۲۰۲۱ را با پرچم‌دارهای جدید سامسونگ آغاز کردیم. سامسونگ اولین شرکتی بود که در سال ۲۰۲۱ میلادی، گوشی‌های جدید خود را معرفی کرد .',
        img_header:"https://cdn01.zoomit.ir/2021/2/samsung-galaxy-s21-on-green-cutting-mat.jpg?w=1920",
        sliderImg1:'https://i4.hurimg.com/i/hurriyet/75/0x0/602513607af5073e90d2e47c.jpg',
        sliderImg2:'https://www.zarrinhoor.com/wp-content/uploads/2022/01/155378-phones-review-hands-on-samsung-galaxy-s21-ultra-image1-luae09ici4.jpg',
        sliderImg3:'https://images.anandtech.com/doci/16488/X-T30_DSF4234_678x452.jpg',
        sliderImg4:'https://www.trustedreviews.com/wp-content/uploads/sites/54/2021/01/DSC01626-scaled.jpeg',
        sliderImg5:'https://techrato.com/wp-content/uploads/2022/01/analisis-samsung-galaxy-s21-ultra-5g-2215809.jpg',
        sliderImg6:'https://specphone.com/web/wp-content/uploads/2021/01/Preview-Samsung-Galaxy-S21-Ultra-5G-SpecPhone-0001-768x512.jpg',
        sliderImg7:'https://www.deccanherald.com/sites/dh/files/styles/article_detail/public/articleimages/2021/02/02/sgs21u5g-cov-s1-946640-1612266957.jpg?itok=eJg7h7c-',
        sliderImg8:'https://awsimages.detik.net.id/community/media/visual/2021/01/15/samsung-galaxy-s21-ultra_169.jpeg?w=700&q=90',
    },
    {
        id: 6,
        text_header1:'Samsung Galaxy S22 Ultra',
        text_header2:'سری گلکسی S سامسونگ پرچم‌داران غیرتاشوی شرکت کره‌ای هستند که محبوبیت زیادی بین کاربران دارند. در شرایطی که مدل‌های سری S21 از جمله گلکسی S21 اولترا، در رده‌ی قدرتمندترین پرچم‌دارهای موجود در بازار جای می‌گرفتند و به‌خصوص در بخش دوربین حرف‌های زیادی برای گفتن داشتند، امسال سامسونگ تصمیم گرفت استراتژی موفق نسل قبل را با تغییرات جزئی؛ اما مهم ادامه دهد و مدل‌های سال ۲۰۲۲ را با اندکی تفاوت نسبت به سال قبل راهی بازار کند.  ',
        img_header:"https://cdn01.zoomit.ir/2022/2/samsung-galaxy-s22-plus.jpg?w=1920",
        sliderImg1:'https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/Untitled2969.png',
        sliderImg2:'https://media.cnn.com/api/v1/images/stellar/prod/220223142400-galaxy-s22-plus-lead.jpg?q=h_2085,w_3706,x_0,y_0',
        sliderImg3:'https://www.thegate.ca/wp-content/uploads/2022/02/0K4A2008.jpg',
        sliderImg4:'https://fs.npstatic.com/userfiles/7687254/image/Samsung_Galaxy_S22/NextPit_Samsung_Galaxy_S22-w810h462.jpg',
        sliderImg5:'https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/Samsung_Galaxy_S_Series_Hands_On_29_von_3336.png',
        sliderImg6:'https://cdn01.vulcanpost.com/wp-uploads/2022/04/samsung-galaxy-s22-ultra-performance-001.jpg',
        sliderImg7:'https://www.deccanherald.com/sites/dh/files/articleimages/2022/03/29/sgs22u-cov-sho-sel-1-1095528-1648557160.jpg',
        sliderImg8:'https://cdn.andro4all.com/andro4all/2022/02/Parte-trasera-del-Samsung-Galaxy-S22-Ultra-rojo.jpg',
    },
]

export default phonedatapage